FROM IMAGE as build
ARG app_dns
ARG jupyter_dns
#RUN echo "dns name is ${app_dns}"
RUN apt-get -y update && \
    echo "deb http://security.debian.org/debian-security stable-security/updates main" >> /etc/apt/sources.list && \
	apt-get -y install sed 
#RUN sed -i  "s/APPDNS/${app_dns}/g" /app/.env 
#RUN sed -i  "s/JUPYTERDNS/${jupyter_dns}/g" /app/.env && cat /app/.env
RUN npm install --silent
RUN npm rebuild node-sass
RUN npm run build

#prepare nginx
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html/mi


