# dockerfile: Dockerfile
# dockerfile: Dockerfile.qa
# dockerfile: Dockerfile.stage
# dockerfile: Dockerfile.prod.

version: '3.9'
services:
  ui-cypress-test:
    container_name: cpv-nextgen-ui
    build: .
    dockerfile: Dockerfile-server-start-for-cypresss
    environment:
      - NODE_PATH=src/
    ports:
      - 3030:3030


