FROM IMAGE as build
ARG app-dns
ARG jupyter-dns
RUN echo "dns name is ${dns}"
RUN apt-get -y update 
RUN apt-get -y install sed  
RUN sed -i  "s/APPDNS/${app-dns}/g" /app/.env 
RUN sed -i  "s/JUPYTERDNS/${jupyter-dns}/g" /app/.env && cat /app/.env
RUN npm install --silent
RUN npm rebuild node-sass
RUN npm run build

#prepare nginx
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html


