FROM node:14
ENV APP_FILE package.json
ENV APP_HOME /usr/apps
WORKDIR $APP_HOME
ADD $APP_FILE $APP_HOME/$APP_FILE
RUN apt-get update && \
    apt-get install -y xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 && \
    apt-get install -y libgtk-3-0 libgbm-dev  libxtst6 xauth 
RUN npm install
COPY . .
EXPOSE 3030
ENV PORT 3030
ENTRYPOINT ["sh", "-c"]
CMD ["npm run start"]
