# dockerfile: Dockerfile
# dockerfile: Dockerfile.qa
# dockerfile: Dockerfile.stage
# dockerfile: Dockerfile.prod.

version: '3.9'
services:
  ui-cypress-test:
    container_name: ui-cypress-test
    build: 
      context: .
      dockerfile: Dockerfile-start-server
    environment:
      - NODE_PATH=src/
    ports:
      - 3030:3030
  nginx:
    container_name: nginx
    image: nginx:1.19
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d


