const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';
const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
const SET_THEME = 'SET_THEME';
const SET_NAVIGATION_DATA = 'SET_NAVIGATION_DATA';
const TOGGLE_MENU = 'TOGGLE_MENU';
const SELECTED_SITE = 'SELECTED_SITE';
const FUNCTION_TEXT = 'FUNCTION_TEXT';
const MOLECULE_ID = 'MOLECULE_ID';
const LOAD_TEMPLATE = "LOAD_TEMPLATE"
const MATBATCH_INFO = "MATBATCH_INFO"
export {
	SHOW_LOADING,
	HIDE_LOADING,
	SHOW_NOTIFICATION,
	HIDE_NOTIFICATION,
	SET_THEME,
	SET_NAVIGATION_DATA,
	TOGGLE_MENU,
	SELECTED_SITE,
	FUNCTION_TEXT,
	MOLECULE_ID,
	LOAD_TEMPLATE,
	MATBATCH_INFO
};
