const SHOW_LOADING = "SHOW_LOADING";
const HIDE_LOADING = "HIDE_LOADING";
const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
const SET_THEME = "SET_THEME";
const SET_NAVIGATION_DATA = "SET_NAVIGATION_DATA";
const TOGGLE_MENU = "TOGGLE_MENU";
const FUNCTION_TEXT = "FUNCTION_TEXT";
const MOLECULE_ID = "MOLECULE_ID";
const LOAD_TEMPLATE = "LOAD_TEMPLATE";
const MATBATCH_INFO = "MATBATCH_INFO";
const PAGE_IDENTIFIER = "PAGE_IDENTIFIER";
const TEMP_ADDITIONAL = "TEMP_ADDITIONAL";
const AUTHENTICATED = "AUTHENTICATED";
const INITIAL_DATA = 'INITIAL_DATA';
const NETWORK_ERROR = "NETWORK_ERROR";
const IS_SAML_SIGN = "IS_SAML_SIGN";
export {
	SHOW_LOADING,
	HIDE_LOADING,
	SHOW_NOTIFICATION,
	HIDE_NOTIFICATION,
	SET_THEME,
	SET_NAVIGATION_DATA,
	TOGGLE_MENU,
	FUNCTION_TEXT,
	MOLECULE_ID,
	LOAD_TEMPLATE,
	MATBATCH_INFO,
	PAGE_IDENTIFIER,
	TEMP_ADDITIONAL,
	AUTHENTICATED,
	INITIAL_DATA,
	NETWORK_ERROR,
	IS_SAML_SIGN
};
