export const TOGGLE_BOXED_LAYOUT = 'TOGGLE_BOXED_LAYOUT';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const TOGGLE_NAV_BEHIND = 'TOGGLE_NAV_BEHIND';
export const TOGGLE_FIXED_HEADER = 'TOGGLE_FIXED_HEADER';
export const CHANGE_SIDEBAR_WIDTH = 'CHANGE_SIDEBAR_WIDTH';
export const CHANGE_COLOR_OPTION = 'CHANGE_COLOR_OPTION';
export const CHANGE_THEME = 'CHANGE_THEME';

export const FETCH_POST = 'FETCH_POST';
export const SEND_POST = 'SEND_POST';

export const GET_FILTER_DATA = 'GET_FILTER_DATA';
export const SEND_FILTER_DATA = 'SEND_FILTER_DATA';

export const RESET_CHART = 'RESET_CHART';
export const SELECTED_SITE = 'SELECTED_SITE';
export const SELECTED_DATE_RANGE = 'SELECTED_DATE_RANGE';
export const SELECTED_UNAPPROVED_DATA = 'SELECTED_UNAPPROVED_DATA';

export const GET_CHART_NAME = 'GET_CHART_NAME';
export const GENERATE_CHART = 'GENERATE_CHART';
export const GET_CHART_DATA = 'GET_CHART_DATA';

export const SELECTED_CHART_TYPE = 'SELECTED_CHART_TYPE';
export const SELECTED_X_AXIS = 'SELECTED_X_AXIS';
export const SELECTED_Y_AXIS = 'SELECTED_Y_AXIS';
export const SELECTED_CHART_NAME = 'SELECTED_CHART_NAME';
export const SELECTED_CHART_DESCRIPTION = 'SELECTED_CHART_DESCRIPTION';

export const SELECTED_VIEW = 'SELECTED_VIEW ';
export const SELECTED_VIEW_ID = 'SELECTED_VIEW_ID';
export const SELECTED_VIEW_NAME = 'SELECTED_VIEW_NAME';
export const SELECTED_VIEW_STATUS = 'SELECTED_VIEW_STATUS';
export const SELECTED_VIEW_VERSION = 'SELECTED_VIEW_VERSION';

export const SELECTED_CHART_ID = 'SELECTED_CHART_ID';
export const SELECTED_CHART_VERSION = 'SELECTED_CHART_VERSION';
export const SELECTED_CHART_DATA = 'SELECTED_CHART_DATA';
export const CHART_MAPPING = 'CHART_MAPPING';
export const SEND_CHART_DATA = 'SEND_CHART_DATA';
export const SEND_CHART_LAYOUT = 'SEND_CHART_LAYOUT';

export const GET_BATCH_COVERAGE = 'GET_BATCH_COVERAGE';
export const PARAMETER_TABLE_DATA = 'PARAMETER_TABLE_DATA';
export const BATCH_DATA = 'BATCH_DATA';
export const TOTAL_MOL_BATCHES = 'TOTAL_MOL_BATCHES';
export const TOTAL_FILE_BATCHES = 'TOTAL_FILE_BATCHES';

// Report Designer Actions

export const SELECTED_REPORT_ID = 'SELECTED_REPORT_ID';
export const SCREEN_CHANGE = 'SCREEN_CHANGE';
export const LOADED_LAYOUT = 'LOADED_LAYOUT';
export const REPORT_LOAD = 'REPORT_LOAD';
export const GEN_LOAD = 'GEN_LOAD';



//login page actions
export const LOGIN_DETAILS = 'LOGIN_DETAILS';
export const REDIRECT_URL = 'REDIRECT_URL';

//view creation actions
export const SAVE_FUNCTIONS = 'SAVE_FUNCTIONS';
export const SAVE_AS_FUNCTIONS = 'SAVE_AS_FUNCTIONS';
export const MATH_EDITOR = 'MATH_EDITOR';
export const FUNCTION_NAME = 'FUNCTION_NAME';

export const FUNCTION_MAP = 'FUNCTION_MAP';
export const PARAMETER_MAP = 'PARAMETER_MAP';

export const VIEW_PARAM_DATA = 'VIEW_PARAM_DATA';
export const SELECTED_PARAM_DATA = 'SELECTED_PARAM_DATA';
export const BATCH_COVERAGE_DATA = 'BATCH_COVERAGE_DATA';
export const SELECTED_VARIABLE = 'SELECTED_VARIABLE';
export const SUMMARY_TABLE_DATA = 'SUMMARY_TABLE_DATA';

export const SELECTED_PARAM_TYPE = 'SELECTED_PARAM_TYPE';
export const VIEW_FUNCTION_MAP = 'VIEW_FUNCTION_MAP';
export const VIEW_PARAM_MAP = 'VIEW_PARAM_MAP';
export const IS_LOAD_VIEW = 'IS_LOAD_VIEW';
export const IS_NEW_VIEW = 'IS_NEW_VIEW';
export const RESET_VIEW = 'RESET_VIEW';
export const NEW_COLUMN = 'NEW_COLUMN';
export const VIEW_FUNCTION_NAME = 'VIEW_FUNCTION_NAME';
export const MATH_VALUE = 'MATH_VALUE';
export const LOAD_VIEW_RESPONSE = 'LOAD_VIEW_RESPONSE';

export const DRUG_SUBSTANCE = 'DRUG_SUBSTANCE';
export const DRUG_LOAD = 'DRUG_LOAD';

export const IS_TARGET_VAR = 'IS_TARGET_VAR';
export const LOAD_VIEW_TABLE_DATA = 'LOAD_VIEW_TABLE_DATA';
