export const TOGGLE_BOXED_LAYOUT = 'TOGGLE_BOXED_LAYOUT';
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSED_NAV';
export const TOGGLE_NAV_BEHIND = 'TOGGLE_NAV_BEHIND';
export const TOGGLE_FIXED_HEADER = 'TOGGLE_FIXED_HEADER';
export const CHANGE_SIDEBAR_WIDTH = 'CHANGE_SIDEBAR_WIDTH';
export const CHANGE_COLOR_OPTION = 'CHANGE_COLOR_OPTION';
export const CHANGE_THEME = 'CHANGE_THEME';

export const FETCH_POST = 'FETCH_POST';
export const SEND_POST = 'SEND_POST';

export const GET_FILTER_DATA = 'GET_FILTER_DATA';
export const SEND_FILTER_DATA = 'SEND_FILTER_DATA';

export const RESET_CHART = 'RESET_CHART';
export const SELECTED_SITE = 'SELECTED_SITE';
export const SELECTED_DATE_RANGE = 'SELECTED_DATE_RANGE';
export const SELECTED_UNAPPROVED_DATA = 'SELECTED_UNAPPROVED_DATA';

export const GET_CHART_NAME = 'GET_CHART_NAME';
export const GENERATE_CHART = 'GENERATE_CHART';
export const GET_CHART_DATA = 'GET_CHART_DATA';

export const SELECTED_CHART_TYPE = 'SELECTED_CHART_TYPE';
export const SELECTED_X_AXIS = 'SELECTED_X_AXIS';
export const SELECTED_Y_AXIS = 'SELECTED_Y_AXIS';
export const SELECTED_CHART_NAME = 'SELECTED_CHART_NAME';
export const SELECTED_CHART_DESCRIPTION = 'SELECTED_CHART_DESCRIPTION';

export const SELECTED_VIEW = 'SELECTED_VIEW ';
export const SELECTED_VIEW_ID = 'SELECTED_VIEW_ID';
export const SELECTED_VIEW_NAME = 'SELECTED_VIEW_NAME';
export const SELECTED_VIEW_STATUS = 'SELECTED_VIEW_STATUS';
export const SELECTED_VIEW_VERSION = 'SELECTED_VIEW_VERSION';

export const SELECTED_CHART_ID = 'SELECTED_CHART_ID';
export const SELECTED_CHART_VERSION = 'SELECTED_CHART_VERSION';
export const SELECTED_CHART_DATA = 'SELECTED_CHART_DATA';
export const CHART_MAPPING = 'CHART_MAPPING';
export const SEND_CHART_DATA = 'SEND_CHART_DATA';
export const SEND_CHART_LAYOUT = 'SEND_CHART_LAYOUT';

export const GET_BATCH_COVERAGE = 'GET_BATCH_COVERAGE';
export const PARAMETER_TABLE_DATA = 'PARAMETER_TABLE_DATA';

// Report Designer Actions

export const SELECTED_REPORT_ID = 'SELECTED_REPORT_ID';
export const SCREEN_CHANGE = 'SCREEN_CHANGE';

export const LOGIN_DETAILS = 'LOGIN_DETAILS';
export const REDIRECT_URL = 'REDIRECT_URL';
